In [3]:
import pandas as pd

df = pd.read_csv("F:\OneDrive\psl-data-analysis\data\psl_cleaned.csv")

In [4]:
team_runs = df.groupby("batting_team")["runs_off_bat"].sum()

team_runs

batting_team
Islamabad United     1964
Karachi Kings        1468
Lahore Qalandars     1504
Multan Sultans       2064
Peshawar Zalmi       1866
Quetta Gladiators    1439
Name: runs_off_bat, dtype: int64

In [ ]:
df.groupby("batting_team")["runs_off_bat"].sum().sort_values(ascending=False)
df  # total runs by each team

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [ ]:
df.groupby("bowler")["wicket_type"].count().sort_values(ascending=False)
df  #Total wickets taken by each player (bowler)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [ ]:
df.groupby("striker")["runs_off_bat"].sum().sort_values(ascending=False)
df  #Total wickets taken by each bowler

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [ ]:
df.groupby("striker")["ball"].count().sort_values(ascending=False)
df  #Total balls faced by each striker

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [ ]:
df.groupby("bowling_team")["extras"].sum().sort_values(ascending=False)
df  #Total extras given by each team

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0

In [ ]:
df.groupby("batting_team")["runs_off_bat"].mean()
df  #Average runs per innings by team

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.2,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7791,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.3,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,1,0.0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
7792,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.4,Islamabad United,Multan Sultans,Imad Wasim,Naseem Shah,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
7793,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.5,Islamabad United,Multan Sultans,Naseem Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,caught,Naseem Shah,0.0,0.0
7794,1416505,2023/24,2024-03-18,"National Stadium, Karachi",2,19.6,Islamabad United,Multan Sultans,Hunain Shah,Imad Wasim,...,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0